GitHub Actions: add empty /etc/vconsole.conf
When installing packages, mkinitcpio complains:

    (12/16) Updating linux initcpios...
    ==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
    ==> Using default configuration file: '/etc/mkinitcpio.conf'
      -> -k /boot/vmlinuz-linux -g /boot/initramfs-linux.img
    ==> Starting build: '6.18.6-arch1-1'
      -> Running build hook: [base]
      -> Running build hook: [systemd]
      -> Running build hook: [autodetect]
      -> Running build hook: [microcode]
      -> Running build hook: [modconf]
      -> Running build hook: [kms]
      -> Running build hook: [keyboard]
      -> Running build hook: [keymap]
      -> Running build hook: [sd-vconsole]
    ==> ERROR: file not found: '/etc/vconsole.conf'
      -> Running build hook: [block]
      -> Running build hook: [filesystems]
      -> Running build hook: [fsck]
    ==> Generating module dependencies
    ==> Creating zstd-compressed initcpio image: '/boot/initramfs-linux.img'
    ==> WARNING: errors were encountered during the build. The image may not be complete.
    error: command failed to execute correctly

This is due to the presence of hook sd-vconsole, which requires
/etc/vconsole.conf to be present (documentation of this file:
https://wiki.archlinux.org/title/Linux_console/Keyboard_configuration ).

This issue was previously reported in
https://bbs.archlinux.org/viewtopic.php?id=310236