compare_base.py: do not verify the signature of package databases when comparing versions
core.db is not signed. Without SigLevel configuration, pacman now reports:

    error: failed retrieving file 'core.db.sig' from
    fastly.mirror.pkgbuild.com : The requested URL returned error: 404

This configuration is actually done in the official `pacman.conf`
packaged in `pacman`:
https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/blob/4ee8983653633d6fad7b2b9d6c35027c9705de5d/pacman.conf#L44

    # By default, pacman accepts packages signed by keys that its local keyring
    # trusts (see pacman-key and its man page), as well as unsigned packages.
    SigLevel    = Required DatabaseOptional
    LocalFileSigLevel = Optional